#!/usr/bin/env bash
# SSH client configuration
# file with user config
Host *
IdentityFile ~/.ssh/school
PasswordAuthentication no
SendEnv LANG LC_*
HashKnownHosts yes
GSSAPIAunthentication yes
GSSAPIDelegateCredentials no
